# Generated by Django 5.0.6 on 2024-05-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('sidePanel', models.CharField(max_length=100)),
                ('externalBays', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Системный блок',
                'verbose_name_plural': 'Системные блоки',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('coreCount', models.IntegerField()),
                ('boostClock', models.DecimalField(decimal_places=2, max_digits=6)),
                ('integratedGraphics', models.CharField(max_length=100)),
                ('coreClock', models.FloatField()),
                ('TDP', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Центральный процессор',
                'verbose_name_plural': 'Ценральные процессоры',
            },
        ),
        migrations.CreateModel(
            name='CPUCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('fanRPM', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('noiseLevel', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Кулер',
                'verbose_name_plural': 'Кулеры',
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('chipSet', models.CharField(max_length=100)),
                ('coreClock', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('boostClock', models.FloatField()),
                ('length', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Графический процессор',
                'verbose_name_plural': 'Графические процессоры',
            },
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('socket', models.CharField(max_length=100)),
                ('memoryMax', models.IntegerField()),
                ('formFactor', models.CharField(max_length=100)),
                ('memorySlots', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('mode', models.IntegerField()),
                ('maxSupportedMemory', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ОС',
                'verbose_name_plural': 'ОС',
            },
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('wattage', models.IntegerField()),
                ('efficiencyRating', models.CharField(max_length=100)),
                ('modular', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('modules', models.CharField(max_length=100)),
                ('CASLatency', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
            },
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('formFactor', models.CharField(max_length=100)),
                ('cache', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'SSD',
                'verbose_name_plural': 'SSD',
            },
        ),
    ]
